DROP TABLE #__asinustimetracking_user;
DROP TABLE #__asinustimetracking_roles;
DROP TABLE #__asinustimetracking_services;
DROP TABLE #__asinustimetracking_selection;
DROP TABLE #__asinustimetracking_userservices;
DROP TABLE #__asinustimetracking_entries;
DROP TABLE #__asinustimetracking_costunit;
DROP TABLE #__asinustimetracking_config;
DROP TABLE #__asinustimetracking_pricerange;
